/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'a weathered tree': '一棵饱经风霜的树',
    'Weathered tree': '饱经风霜的树',
    'about & changelog': '关于 & 更新日志',
    'back': '返回',
    'cancel': '取消',
    'achievements': '成就',
    'export save': '导出存档',
    'field': '田地',
    'hard reset': '硬重置',
    'help': '帮助',
    'import save': '导入存档',
    'number format': '数字格式',
    'player stats': '玩家统计',
    'import': '导入',
    'save now': '立即保存',
    'seeds': '种子',
    'Settings': '设置',
    'Undo': '撤销',
    'to clipboard': '复制到剪切板',
    'preferences': '首选项',
    'Example': '例如',
    'Examples': '例如',
    'none': '无',
    'Loaded local save': '载入本地存档',
    'Notation': '符号',
    'Notation description': '符号说明',
    'Player Statistics': '玩家统计',
    'precision': '精确',
    'The game moved to': '游戏已移至',
    'time': '时间',
    'About': '关于',
    'Changelog': '更新日志',
    'Consumption': '消耗',
    'cost': '成本',
    'delete': '删除',
    'detailed stats / bonuses': '详细数据/奖金',
    'Ethereal Farm': '空灵农场',
    'Buy': '购买',
    'Current amount': '当前数量',
    'Current season': '当前季节',
    'have of this crop': '有这样的作物',
    'Production': '生产',
    'Production bonus: +': '生产加成: +',
    'Season change in': '季节变化将在',
    'Seeds': '种子',
    'Spring': '春季',
    'Summer': '夏季',
    'Autumn': '秋季',
    'Winter': '冬季',
    'Spring Effects': '春季效果',
    'Stats': '统计',
    'ok': '好的',
    'prod': '产出',
    'See Completed Upgrades': '查看完成的升级',
    'see unlocked crops': '查看解锁的农作物',
    'Short-lived plant. Time left': '寿命短的植物。 剩下的时间',
    'Show breakdown of multipliers and bonuses and other detailed stats.': '显示乘数，奖金和其他详细统计信息的细目。',
    'Show the crop dialog with unlocked plants.': '显示带有未锁定植物的作物对话框。',
    'The image below shows an optimal configuration to use for watercress copying: the single watercress duplicates the production of 4 blackberries': '下图显示了用于西洋菜复制的最佳配置：单个西洋菜复制了4个黑莓的生产',
    'This tree needs to be rejuvenated first. Requires spores.': '这棵树需要首先恢复活力。 需要孢子。',
    'housand': '数千',
    'Improves production of blackberry by 25% (multiplicative': '将黑莓产量提高25％（成倍增加',
    'Improves production of blueberry by 25% (multiplicative': '使蓝莓产量提高25％（成倍增加',
    'Num planted of this type': '种植这种类型的数量',
    'Unlocked crops...': '解锁的农作物...',
    'Expected production/sec': '预期产量/秒',
    'Planted': '种植',
    'Short-lived plant. Total lifetime': '寿命短的植物。 总寿命',
    'download': '下载',
    'Manually saved state locally': '手动保存到本地',
    'reset': '重置',
    'Save copied to clipboard': '复制存档到剪贴板',
    'Use exponent notation, and the exponents are always multiples of 3. E.g. 10e6 for 10 million': '使用指数表示法，并且指数始终是3的倍数。 10e6是千万',
    'Always uses exponents, such as 2e4 for 20000 (4 zeroes': '始终使用指数，例如2e4表示20000（4个零',
    'Change the displayed number format used for most costs, amounts, percentages, etc...': '更改显示的数字格式，用于大多数成本，金额，百分比等等...',
    'Formats': '格式',
    'Latin suffixes': '拉丁后缀',
    'Latin suffixes, but only up to T (trillion, 1e12), then switches to engineering notation': '拉丁后缀，但最多为T（万亿，1e12），然后切换为工程符号',
    'Latin suffixes, but only up to U (undecillion, 1e36), then switches to engineering notation': '拉丁后缀，但最多不超过U（十进制，1e36），然后切换为工程符号',
    'exponential function for logarithm 10 notation': '对数10表示法的指数函数',
    'exponential function for natural log notation. Here, e = 2.71828...': '用于自然对数符号的指数函数。 本游戏中 e = 2.71828 ...',
    'Engineering': '工程符号',
    'engineering': '工程符号',
    'hybrid T': '混合T',
    'Hybrid T': '混合T',
    'hybrid U': '混合U',
    'Hybrid U': '混合U',
    'scientific': '科学计数法',
    'Scientific': '科学计数法',
    'suffixes latin': '拉丁文后缀',
    'Suffixes latin': '拉丁文后缀',
    'etc...': '等等...',
    'Permanent crop & watercress copying': '永久性作物和西洋菜复制',
    'Help': '帮助',
    'Upgrades': '升级',
    'Dynamic help dialogs': '动态帮助对话框',
    'Keyboard shortcuts': '快捷键',
    'Main help': '关键帮助',
    'More help topics will appear here as the game progresses. Any in-game help dialog that pops up will become permanently available here once it\'s unlocked': '随着游戏的进行，更多帮助主题将出现在此处。 解锁后，任何弹出的游戏内帮助对话框都将在此处永久可用',
    'Number format help': '数字格式帮助',
    'empty field': '空地',
    'fruit ability upgrade': '水果能力升级',
    'fruit: move to sacrificial pool or from sacrificial pool to storage.': '水果：转移到牺牲池或从牺牲池转移到存储。',
    'You can click resources in the resource panel to see more detailed breakdown. You can click fullgrown crops to see detailed stats. As the game progresses, more types of information may appear in there.': '您可以在资源面板中单击资源以查看更多详细信息。 您可以单击成熟的农作物以查看详细的统计信息。 随着游戏的进行，可能会在其中显示更多类型的信息。',
    'You unlocked your first permanent type of plant. Plants like this stay on the field forever, keep producing forever, and have much more powerful production upgrades too.': '您解锁了您的第一个永久类型的植物。 这样的工厂将永远留在田间，永远保持生产，并且还具有更强大的生产升级能力。',
    'You unlocked your first upgrade! Check the "upgrades" tab to view it. Upgrades can unlock new crops, upgrade existing crops, or various other effects. Upgrades usually cost': '您已解锁首次升级！ 检查“升级”标签以查看它。 升级可以解锁新作物，升级现有作物或其他各种效果。 升级通常需要花费',
    'achievements production bonus': '成就生产加成',
    'blueberry.': '蓝莓.',
    'deleted': '删除的',
    'duration': '持续了',
    'ferns': '蕨类植物',
    'highest production': '最高产量',
    'highest resources': '最高资源',
    'planted (permanent': '种植的 (永久',
    'planted (watercress': '种植的 (西洋菜',
    'start time': '开始时间',
    'total earned': '累计获得',
    'Crowded': '拥挤',
    'the entire field full of berries': '整个田野长满了浆果',
    'Berries': '浆果',
    'champignon, consumed': '香菇，消耗',
    'champignon.': '香菇。',
    'mushroom.': '蘑菇.',
    'clover': '三叶草',
    'currant': '黑醋栗',
    'Current production boost for unspent resin': '未消耗树脂的当前产量增长',
    'fern choice': '蕨类植物的选择',
    'Production (seeds': '生产 (种子',
    'Resin': '树脂',
    'Richer ferns': '蕨类植物更丰富',
    'Slower ferns': '蕨类植物放缓',
    'Spores': '孢子',
    'mushroom': '蘑菇',
    'Needs more seeds, requires berries as neighbors.': '需要更多的种子，需要浆果作为邻居。',
    'Satisfied': '满意',
    'active': '激活',
    'After consumption': '消费后',
    'Cooldown time': '冷却时间',
    'Running time': '运行时间',
    'Deleted cranberry, got back': '删除蔓越莓，得到',
    'sun ability: berries get a production bonus and aren\'t negatively affected by winter': '太阳能力：浆果获得生产奖金，并不会受到影响冬季',
    'Sun activated, berries get a boost and aren\'t affected by winter': '太阳激活，浆果得到增强，不受冬季影响',
    'Total cycle': '总周期',
    'ready in': '冷却',
    'Received: "mist ability': '收到：“薄雾能力',
    'A possible strategy: keep fruits with good abilities you like. Sacrifice any other surpluss fruits, so you can use the essence to upgrade the good fruits.': '可能的策略：保留自己喜欢的能力的成果。 牺牲任何其他多余的水果，因此您可以使用精华液来升级优质水果。',
    'active fruit': '活跃的水果',
    'fruit': '水果',
    'Fruit collection': '水果集合',
    'Fruit dropped: bronze apple. weather cooldown III, growing speed II': '掉落的水果：青铜苹果。 天气冷却III，成长速度II',
    'sacrificial fruit pool': '牺牲果池',
    'stored fruits': '储存的水果',
    'The tree reached level 5 and dropped a fruit! Fruits provide boosts and can be upgraded with fruit essence. Essence is gained by sacrificing fruits, and all full amount of fruit essence can be used for upgrading all other fruits at the same time. See the "fruit" tab, it also has a more extensive help dialog for fruits.': '树达到了5级，掉了一个果子！ 水果可以增强营养，并可以用水果精华进行升级。 牺牲果实即可获得精华，所有饱满的果实精华可同时用于所有其他果实的升级。 看到“水果”标签，它也有一个更广泛的水果帮助对话框。',
    'Tree leveled up to: young tree, level 5. Consumed: 43.7K spores. Tree boost: 25%. Resin added: 0.966. Total resin ready': '树木升级到：幼树，等级5。消耗：43.7K孢子。 树木助力：25％。 树脂添加量：0.966。 总树脂准备就绪',
    'Bronze apple, fruit tier': '青铜苹果，水果层',
    'Trillion': '万亿',
    'Bronze apple': '青铜苹果',
    'click ability to view or level up': '点击能力查看或升级',
    'Current level': '当前等级',
    'Click the fruit logo in the fruit dialog to mark as favorite and alter color effects (visual effect only).': '点击水果对话框中的水果图标，将其标记为最喜欢的，并改变颜色效果(仅限视觉效果)。',
    'All fruit essence is available for all fruits, leveling up an ability in one fruit does not consume any fruit essence for other fruits. Example: if you have 50 fruit essence and 3 fruits, then you can use 50 essence in fruit 1, you can also use 50 essence in fruit 2, and you can also use 50 essence in fruit 3, and in any future fruits as well. If you now sacrifice a fruit that gives 10 essence, you have 10 more essence available for all the others.': '所有水果都可以获得所有的水果精华，升级一个水果的能力不会消耗其他水果的任何水果精华。例如:如果你有50个水果精华和3个水果，那么你可以在水果1中使用50精华，你也可以在水果2中使用50精华，你也可以在水果3中使用50精华，以及在未来的任何水果中也可以使用50精华。如果你现在牺牲了一个可以提供10种精华的水果，你就可以为其他所有水果提供10种更多的精华。',
    'Higher tier fruits may have more abilities, and abilities provide more boost.': '较高等级的水果可能具有更多的能力，而能力则提供了更大的推动力。',
    'Leveling up abilities permanently affects this fruit, you cannot undo it. This only matters if this fruit has more than one ability so that you have to choose which ones to level up. And if unhappy with this fruit, you can always wait for a next one and sacrifice this one.': '升级能力会永久影响该果实，您无法撤消它。 这仅在此水果具有多个功能的情况下才重要，因此您必须选择要升级的水果。 如果对这种水果不满意，您总是可以等待下一个并牺牲这个。',
    'Next level': '下一级',
    'Reached tree level': '到达树等级',
    'Reduces plants growing time': '减少植物的生长时间',
    'Reduces weather ability cooldown time': '减少天气能力的冷却时间',
    'The active and stored fruits do not get sacrificed and stay after transcension.': '活跃的果实和储存的果实不会被牺牲，而在超越之后会保留下来。',
    'to active slot': '到活跃插槽',
    'to storage slot': '到存储插槽',
    'to sacrificial pool': '到牺牲池',
    'Level': '等级',
    'Progress to next level': '进入下一个等级的进度',
    'morel': '羊肚菌',
    'Received: "rainbow ability': '收到：“彩虹能力',
    'currant.': '黑醋栗。',
    'Warning: this overwrites your current game!': '警告：这会覆盖您当前的游戏！',
    'You need to gather some resources. Click a fern to get some.': '您需要收集一些资源。 单击蕨类植物得到一些。',
    'Rainbow: benefits flowers when active': '彩虹：激活时有益花朵',
    'Played for 1 days': '玩了1天',
    'Improves production but also consumption of morel by 25% (multiplicative': '提高产量，但羊肚菌的消耗提高25％（成倍增加',
    'goji': '枸杞',
    'Currant': '黑醋栗',
    'available: "Upgrade morel': '可用：“升级羊肚菌',
    '+50% bonus to berry seed production': '浆果种子产量增加50％',
    'Summer Effects': '夏季效果',
    'Four seasons': '四季',
    'Long weather': '长时间天气',
    'Strong weather': '强天气',
    'weather choice': '天气选择',
    'Basic tree boost bonus': '基础树提升奖励',
    'boost here': '提升这里',
    'boosts berries 25% (additive': '提升浆果25%(额外',
    'boosts flowers 25% (additive': '提升花25%(额外',
    'boosts mushrooms 25% (additive': '提升蘑菇25%(额外',
    'essence': '精华',
    'delete tokens': '删除令牌',
    'Extra fruit slot': '额外的水果插槽',
    'Faster growing': '快速生长',
    'fern': '蕨类植物',
    'Fern': '蕨类植物',
    'Fruit': '水果',
    'Goji': '枸杞',
    'Larger field': '更大的田地',
    'Max tree level ever': '最大树等级',
    'mistletoe': '槲寄生',
    'Morel': '龙葵',
    'nettle': '荨麻',
    'Nettle': '荨麻',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'increase winter tree warmth effect 25% (additive) of the original effect. In addition, slightly increase the winter resin bonus and gradually reduce the negative winter effect.': '冬季树木温暖效果在原效果基础上增加25%(加值)。另外，稍微增加冬季树脂加成，逐渐减少冬季的负面影响。',
    'Improves boost of nettle by 50% (additive': '提高荨麻50%的提升(附加',
    'upgrades are permanent and the resin is not refundable. You can also spend resin on plants in the ethereal field instead.': '升级是永久的，树脂是不退款的。你也可以在以太场的植物上使用树脂。',
    'Improve autumn': '提升秋季',
    'Improve spring': '提升春季',
    'Improve summer': '提升夏季',
    'Improve winter': '提升冬季',
    'III: Electrum': 'III: 银金矿',
    'Zinc apple, fruit tier': '锌苹果，水果层',
    'Winter hardening': '冬季硬化',
    'white lotus': '白莲',
    'Using this to level up fruit abilities does not consume the global essence. Every fruit can use all the essence.': '使用这个来升级水果能力不会消耗全局精华。每一种水果都可以使用所有的精华。',
    'Transcended 1 times': '超越1次',
    'Transcend': '超越',
    'Total resin earned ever': '树脂总收入',
    'Lasts through transcensions.': '通过超越持续。',
    'This ethereal upgrade is non-refundable and permanent. Lasts through transcensions.': '这次升级是不可退款的，而且是永久的。通过霍妮持续。',
    'They cost resin, so choose wisely.': '它们很贵，所以要明智地选择。',
    'Ten resin': '十个树脂',
    'Recoup on delete (100%): 15 resin': '回收删除(100%):15树脂',
    'Reached winter and seen all seasons': '达到了冬天，看到了所有的季节',
    'Played for 7 days': '玩了7天',
    'mistletoe crop in the basic field. This crop will allow leveling up the ethereal tree through a basic field mechanic giving twigs, and the ethereal tree levels then allow to get next sets of ethereal upgrades and crops. The mistletoe will become available in the basic field when mushrooms become available and then needs to then be unlocked with a regular upgrade first as usual. Then it can be planted next to the basic tree to start getting twigs. This ethereal upgrade is the first step in that process, and this is ultimately required to progress to next stages of the game.': '基础田的槲寄生作物。这种作物将允许通过基本的田地机制给予树枝来升级以太树，然后以太树等级允许获得下一套以太升级和作物。槲寄生将会在蘑菇可用时在基本的领域，然后需要然后像往常一样通过常规升级解锁。然后，它可以被种植在基本树旁边，开始获得树枝。这个空灵升级是这个过程的第一步，这最终需要进入游戏的下一个阶段。',
    'Hundred resin': '百种树脂',
    'gives 100 * n^3 starter': '起始数是100 * n^3',
    'gain an extra storage slot for fruits': '获得一个额外的水果储存槽',
    'crops give various bonuses to the basic field': '庄稼给基础农场带来各种好处',
    'effect': '效果',
    'Earned over 10 resin in total': '总共获得超过10个树脂',
    'Clicked 100 ferns': '点击100蕨类植物',
    'Click the icon of an upgrade or see its tooltip for a more detailed description.': '单击升级图标或查看其工具提示以获得更详细的说明。',
    'Choose an ethereal crop to plant.': '选择一种空灵的作物来种植。',
    'Boosts neighboring mushrooms spores production (without increasing seeds consumption), but negatively affects neighboring berries and flowers, so avoid touching those with this plant': '促进相邻蘑菇孢子的产生(而不增加种子的消耗)，但对相邻的浆果和花有负面影响，所以避免接触这些植物',
    'Boosting spores: 400%. Nerfing neighbor berries and flowers': '提升孢子:400%。削弱邻居的浆果和花朵',
    'basic plants grow up to 60 seconds per upgrade level faster. This is soft-capped for already fast plants, a plant that already only takes 60 seconds, will not get much faster. This improves the higher level slower plants more.': '基本工厂的每个升级级别最多可以增长60秒。 对于已经很快的植物，这是软上限，已经只需要60秒的植物将不会更快。 这样可以使高水平的慢植物得到更多的改善。',
    'Amount from next sacrificed fruits': '下一次牺牲的水果数量',
    'add 2% to the basic tree production bonus per level (additive). For example, if the level 1 basic tree production bonus is normally 5%, it is now 7%, and at tree level 2 it is then 14% instead of': '每一级增加2%的基本树木产量加成(加成)。例如，如果1级的基本树木生产加成通常是5%，现在是7%，而2级树木生产加成则是14%',
    ' Weather boost III (': '天气提升 III (',
    'During winter, the tree provides winter warmth: +50% berry / mushroom / flower stats for crops next to the tree': '在冬季，树提供冬季温暖:+50%浆果/蘑菇/花的作物属性',
    'Harsh conditions: -25% berry / mushroom / flower stats when not next to the tree': '恶劣的条件:-25%的浆果/蘑菇/花属性，当不靠近树时',
    'Resin bonus: 50% more resin added when tree levels up during the winter': '树脂加成:当树木在冬季升级时增加50%的树脂添加量',
    'Unspent resin': '未用树脂',
    'Total resin earned entire game': '游戏迄今获得的树脂总金额',
    'Resin breakdown': '树脂分解',
    'Winter tree warmth: +50% berry / mushroom / flower stats when next to the tree  (current reach: orthogonal, 6 spots': '冬季树木的保暖度：+ 50％浆果/蘑菇/树旁的花朵统计（当前覆盖范围：正交，有6个斑点）',
    'Winter Effects': '冬天效果',
    'winter bonus:': '冬季加成：',
    'morel. Base production: -480B seeds, 122K spores/s. Crop type:': '羊肚菌 基本产量：-480B种子，122K孢子/秒。 作物类型：',
    'mist ability': '雾气能力',
    "Collected upcoming resin": "收集即将到来的树脂",
    'Adds 20%  time duration to the lifespan of watercress (additive), and adds 50% base production excluding the neighbor copying effect. (additive': '将西洋菜的寿命延长20%(额外)，并将基础产量增加50%，排除相邻复制效应。(额外',
    'Undo save time duration is limited to 1 hour. If you undo a long time duration, you\'ll still get the correct amount of resources gained during that time.': '取消保存时间只限于1小时。如果你撤销一个很长的持续时间，你仍然可以获得在那段时间内获得的正确的资源数量。',
    'Undo is saved when doing an action, but with at least 10 seconds of time in-between, so multiple actions in quick succession may all be undone.': '撤消在执行操作时保存，但两者之间至少有10秒的时间，因此快速连续的多个操作都可能撤消。',
    'The tree reached level 8 and is providing another choice, see the new upgrade that provides two choices under "upgrades".': '该树达到了第8级，并提供了另一个选择，请参阅“升级”下提供两个选择的新升级。',
    'Makes the active weather abilities run twice as long, but also twice as long to recharge. This benefits idle play, but gives on average no benefit for active play.': '使激活的天气技能的运行时间增加一倍，同时也增加两倍的恢复时间。这有利于闲散玩耍，但平均而言对积极玩耍没有好处。',
    'Increases all active ability weather effects by 25%. The active abilities recharge time remains the same so this benefits active play more than idle play.': '增加所有主动技能天气效果25%。活跃技能的恢复时间保持不变，所以活跃技能比闲置技能更有好处。',
    'summary': '概要',
    'Once a has fern appeared, letting it sit longer does not change the amount it gives.': '一旦一种蕨类植物出现了，让它久坐并不会改变它给予的数量。',
    'morel.': '羊肚菌。',
    'goji. Base production: 480B seeds/s. Crop type:': '枸杞 基本产量：480B种子/秒。 作物类型：',
    'available: "Upgrade currant': '可用：“升级黑醋栗',
    'available: "Unlock morel': '可用：“解锁羊肚菌',
    'available: "Unlock goji': '可用：“解锁枸杞',
    'While enabled, flowers get a boost, and in addition are not affected by winter. This active ability is enabled using its icon button at the top or the "3" key.': '启用后，花朵会得到增强，此外不受冬季影响。 使用顶部的图标按钮或“ 3”键可启用此主动技能。',
    'Tree leveled up to: young tree, level 6. Consumed: 394K spores. Tree boost: 30%. Resin added: 1.1. Total resin ready': '树木升至：幼树，等级6。消耗：394K孢子。 树木助力：30％。 树脂添加：1.1。 总树脂准备就绪',
    'The tree reached level 6 and discovered the rainbow ability!': '树达到了6级并发现了彩虹的能力！',
    'rainbow ability: rainbow ability: flowers get a boost and aren\'t negatively affected by winter': '彩虹能力：彩虹能力：花朵得到增强，不会受到冬季的负面影响',
    'Improves production of currant by 25% (multiplicative': '提高黑醋栗产量25％（成倍增加',
    'Mist: benefits mushrooms when active': '薄雾：活跃时有益于蘑菇',
    'No stored fruit present in this slot. Fruits in storage slots are kept after transcension, unlike those in the sacrificial pool. To get a fruit in here, click a fruit elsewhere and use its dialog to move it to storage. (': '该插槽中没有储存的水果。 与牺牲池中的水果不同，存储槽中的水果在超载后会保留下来。 要在此处获取水果，请单击其他位置的水果，然后使用其对话框将其移至存储位置。 （',
    'No active fruit present in this slot. Only the fruit in the active slot will grant the abilities. The fruit in the active slot is kept after transcensions, just like those in storage. To get a fruit in here, click a fruit elsewhere and use its dialog to move it to the active slot. (': '该插槽中没有活性水果。 只有活动插槽中的水果才会授予此能力。 主动存储区中的水果经过超验后会保留下来，就像存储时一样。 要在此处获取水果，请在其他位置单击水果，然后使用其对话框将其移至活动插槽。 （',
    'No fruit present in this sacrificial pool slot. Fruits in here will be turned into fruit essence on the next transcension. To get a fruit in here, click a fruit elsewhere and use its dialog to move it to the sacrificial pool. (': '此牺牲池槽中没有水果。 下一次超越时，这里的水果将变成水果的本质。 要在此处获取水果，请单击其他位置的水果，然后使用其对话框将其移至牺牲池。 （',
    'Planted 50 or more permanent plants over the course of the game': '在游戏过程中种植了50株或更多的永久植物',
    'No active fruit present in this slot. Only the fruit in the active slot will grant the abilities. The fruit in the active slot is kept after transcensions, just like those in storage. To get a fruit in here, click a fruit elsewhere and use its dialog to move it to the active slot.': '该插槽中没有活跃水果。 只有活动插槽中的水果才会授予此能力。 主动存储区中的水果经过超验后会保留下来，就像存储时一样。 要在此处获取水果，请在其他位置单击水果，然后使用其对话框将其移至活动插槽。',
    'You can move fruits between the active, stored and sacrificial slots with the buttons in the fruit dialog. You can only have one active fruit and only the abilities of the active fruit have an effect. You can switch the active fruit at any time.': '您可以使用水果对话框中的按钮在活动，存储和牺牲插槽之间移动水果。 您只能拥有一种活跃水果，并且只有活跃水果的能力才会起作用。 您可以随时切换有效水果。',
    'To get more fruit essence, sacrifice fruits by putting them in the sacrificial pool and transcending (available at high enough tree level). The amount of fruit essence of sacrificed fruits depends on their tier (zinc, bronze, ...), the ability levels or how much essence you\'ve used to level them up don\'t matter for this.': '为了获得更多的果实精华，请将果实放入牺牲池中并超越（在足够高的树上可用）来牺牲果实。 牺牲的果实的果实精华量取决于其等级（锌，铜，...），能力等级或您用来使它们升华的精华程度无关紧要。',
    'Fruits have one or more abilities from a random set.': '水果具有随机一组的一项或多项能力。',
    'Fruit help': '水果帮助',
    'Fruit essence used': '使用的水果精华',
    'Fruit essence can be used to level up abilities, increasing their effect. If the fruit has mutliple abilities, click the ability you want to upgrade first.': '水果精华可以用来提升能力，提高其效果。 如果水果具有多种能力，请先单击要升级的能力。',
    'Only the fruit in the active slot will grant the abilities. The fruit in the active slot is kept after transcensions, just like those in storage. To get a fruit in here, click a fruit elsewhere and use its dialog to move it to the active slot.': '只有活动插槽中的水果才会授予此能力。 主动存储区中的水果经过超验后会保留下来，就像存储时一样。 要在此处获取水果，请在其他位置单击水果，然后使用其对话框将其移至活动插槽。',
    'No stored fruit present in this slot. Fruits in storage slots are kept after transcension, unlike those in the sacrificial pool. To get a fruit in here, click a fruit elsewhere and use its dialog to move it to storage.': '该插槽中没有储存的水果。 与牺牲池中的水果不同，存储槽中的水果在超载后会保留下来。 要在此处获取水果，请单击其他位置的水果，然后使用其对话框将其移至存储位置。',
    'No fruit present in this sacrificial pool slot. Fruits in here will be turned into fruit essence on the next transcension. To get a fruit in here, click a fruit elsewhere and use its dialog to move it to the sacrificial pool.': '此牺牲池槽中没有水果。 下一次超越时，这里的水果将变成水果的本质。 要在此处获取水果，请单击其他位置的水果，然后使用其对话框将其移至牺牲池。',
    'Fruits in storage slots are kept after transcension, unlike those in the sacrificial pool. To get a fruit in here, click a fruit elsewhere and use its dialog to move it to storage.': '与牺牲池中的水果不同，存储槽中的水果在超载后会保留下来。 要在此处获取水果，请单击其他位置的水果，然后使用其对话框将其移至存储位置。',
    'Fruits in here will be turned into fruit essence on the next transcension. To get a fruit in here, click a fruit elsewhere and use its dialog to move it to the sacrificial pool.': '下一次超越时，这里的水果将变成水果的本质。 要在此处获取水果，请单击其他位置的水果，然后使用其对话框将其移至牺牲池。',
    'Mist activated, mushrooms produce more spores, consume less seeds, and aren\'t affected by winter': '雾被激活，蘑菇产生更多的孢子，消耗更少的种子，并且不受冬季影响',
    'mist ability: mushrooms produce more spores, consume less seeds, and aren\'t negatively affected by winter': '防雾能力：蘑菇产生更多的孢子，消耗更少的种子，并且不受冬季的负面影响',
    'Have 10 fullgrown cranberry': '有10个成熟的蔓越莓',
    'While enabled, mist temporarily decreases mushroom seed consumption while increasing spore production of mushrooms. In addition, mushrooms are then not affected by winter. This active ability is enabled using its icon button at the top or the "2" key.': '启用后，雾气会暂时减少蘑菇种子的消耗，同时增加蘑菇的孢子产量。 此外，蘑菇也不受冬季的影响。 使用顶部的图标按钮或“ 2”键可启用此主动技能。',
    'Tree leveled up to: young tree, level 4. Consumed: 4.86K spores. Tree boost: 20%. Resin added: 0.847. Total resin ready': '树木升至：幼树，等级4。消耗：4.86K孢子。 树木提升：20％。 树脂添加量：0.847。 总树脂准备就绪',
    'The tree reached level 4 and discovered the mist ability! You now have multiple abilities, only one ability can be active at the same time.': '树达到了4级并发现了雾气能力！ 您现在拥有多种能力，一次只能激活一项能力。',
    'Young sprout': '嫩芽',
    'Tree level production boost to crops': '树木等级的生产促进了农作物的生长',
    'Sun: benefits berries when active': '太阳：活跃时有益于浆果',
    'Resin ready': '准备好树脂',
    'Resin added at next tree level': '在下一棵树级别添加树脂',
    'Reach tree level 10 to unlock transcension': '达到树级10以解锁超越',
    'Next tree level requires': '下一级别树的要求',
    'Boosting neighbors': '促进邻居',
    'Abilities discovered': '发现能力',
    'flower': '花',
    'Expected boost': '预期提升',
    'Clover': '三叶草',
    'none.': '无.',
    'flower.': '花.',
    'clover.': '三叶草。',
    'Boosts neighboring berries and mushrooms, their production but also their consumption. Negatively affected by neighboring nettles.': '促进附近的浆果和蘑菇的生长，提高其产量，同时也提高其消费量。 受到邻近荨麻的负面影响。',
    'boost': '提升',
    'You unlocked your first type of flower. Flowers boost berries and mushrooms. In case of mushrooms, it boosts their spore production, but also increases their seed consumption equally': '您解锁了第一种花。 花会促进浆果和蘑菇的生长。 如果是蘑菇，它可以提高孢子的产量，但同样可以增加种子的消耗',
    'You unlocked the first type of flower! Flowers don\'t produce resources directly, but boost neighboring plants.': '您解锁了第一类花！ 花不直接产生资源，而是促进附近的植物。',
    'Upgraded: fern choice, consumed: 27 spores. Chosen: Slower ferns': '升级：选择蕨类植物，消耗：27孢子。 选择：较慢的蕨类',
    'The image shows a possible good configuration for flower boost: many flowers boost many different berries or mushrooms. Note that in practice the mushroom also needs to touch some berries to get seeds from, not shown in this image.': '该图显示了增强花朵的一种可能的良好配置：许多花朵增强了许多不同的浆果或蘑菇。 请注意，实际上，蘑菇也需要触摸一些浆果才能从中获取种子，此图像未显示。',
    'Potential production means: if mushrooms could consume as many seed as it needs, even if this is more than neighbor berries can produce': '潜在的生产方式是：如果蘑菇可以消耗所需数量的种子，即使这超出了邻居浆果的生产能力',
    'Improves boost of clover by 50% (additive': '将三叶草的提升提高50％（附加',
    'clover, consumed': '三叶草，消耗',
    'available: "Upgrade clover': '可用：“升级三叶草',
    'Upcoming production boost for unspent resin': '即将投产的提升为未用树脂',
    'Total upcoming amount': '即将到来的总额',
    'Total': '累计',
    'To stacks': '堆叠',
    'To consumers': '给消费者',
    'The tree reached level 3 and is providing a choice, see the new upgrade that provides two choices under "upgrades".': '树达到了级别3，并且提供了一个选择，请参阅新的升级，该升级在“升级”下提供了两个选择。',
    'Spores aren\'t used for crops but will automatically level up the tree, which increases the tree progress': '孢子不用于农作物，但会自动使树木变平，从而增加了树木的生长速度',
    'Ferns take 9 instead of 2 minutes to appear, but contain enough resources to make up the difference exactly. This allows to collect more fern resources during idle play, but has no effect on the overall fern income during active play. This starts taking effect only for the next fern that appears.': '蕨类植物需要9分钟而不是2分钟才能出现，但是它们包含的资源足以弥补差异。 这允许在闲置游戏期间收集更多的蕨类资源，但对活跃游戏期间的总体蕨类收入没有影响。 这仅对下一个出现的蕨类开始生效。',
    'Ferns contain on average 25% more resources, but they\'ll appear as often as before so this benefits active play more than idle play. This starts taking effect only for the next fern that appears.': '蕨类植物平均含有25％以上的资源，但它们的出现频率和以前一样，因此，主动游戏比闲置游戏更能受益。 这仅对下一个出现的蕨类开始生效。',
    'Choice upgrade, pick one of the two proposed effects. Choose wisely.': '选择升级，选择两个建议的效果之一。 做出明智的选择。',
    'available: "fern choice': '可用：“蕨类植物选择',
    'Received: "sun ability': '收到：“阳光能力',
    'resin': '树脂',
    'spores': '孢子',
    'While enabled, the sun temporarily increases berry seed production. In addition, berries are then not affected by winter. This active ability is enabled using its icon button at the top or the "1" key.': '启用后，阳光会暂时增加浆果种子的产量。 此外，浆果不受冬季的影响。 可以使用顶部的图标按钮或“ 1”键启用此主动能力。',
    'The tree reached level 2 and discovered the sun ability!': '树达到了2级并发现了日照能力！',
    'Thanks to spores, the tree completely rejuvenated and is now a young sprout, level 1. More spores will level up the tree more. The tree can unlock abilities and more at higher levels. Click the tree in the field for more info.': '多亏了孢子，这棵树才完全恢复了活力，现在是一个年轻的新芽，等级1。更多的孢子会使树的水平更高。 该树可以在更高级别上解锁能力以及更多功能。 单击字段中的树以获取更多信息。',
    'clover. Boosts neighbors: 50%. Does not boost watercress directly, but watercress gets same boosts as its neighbor resource-producing crops. Crop type: flower': '三叶草。 提升邻居：50％。 不直接种植西洋菜，但西洋菜得到与其邻国资源生产作物相同的提振。 作物类型：花',
    'currant. Base production: 686M seeds/s. Crop type:': '黑醋栗。 基本产量：686M种子/秒。 作物类型：',
    'available: "Unlock currant': '可用：“解锁黑醋栗',
    'available: "Unlock clover': '可用：“解锁三叶草',
    'cranberry.': '蔓越莓.',
    'Improves production of cranberry by 25% (multiplicative': '提高蔓越莓产量25%(成倍增加',
    'cranberry, consumed': '蔓越莓，消耗',
    'available: "Upgrade cranberry': '可用：“升级蔓越莓',
    'Requires berries as neighbors to consume seeds to produce spores. Boosted by flowers and nettles. Neighboring watercress can copy its production (but also consumption).': '需要浆果作为邻居来消耗种子产生孢子。长满了花和荨麻。邻近的西洋菜可以模仿它的生产(也可以消费)。',
    'WARNING! if your mushrooms don\'t have enough seeds from neighbors, this upgrade will not help you for now since it also increases the consumption! Get your seeds production up first!': '警告！ 如果您的蘑菇没有来自邻居的足够的种子，那么此升级暂时不会为您提供帮助，因为它还会增加食用量！ 首先提高您的种子产量！',
    'Improves production but also consumption of champignon by 25% (multiplicative': '将香菇的生产量提高25％（成倍增加',
    'This fern is extra bushy! It gave': '这种蕨类植物特别多毛!它给了',
    'The image shows a possible configuration for mushrooms: it extracts some seeds from the berries it touches.': '这张照片展示了蘑菇可能的形态:它从接触的浆果中提取了一些种子。',
    'Spores let the tree level up, unlocking next kinds of bonuses.': '孢子让树升级，解锁下一种奖励。',
    'Spores are used by the tree, but the mushroom is not required to touch the tree.': '孢子被树利用，但蘑菇不需要接触树。',
    'never show again': '不再显示',
    'You unlocked your first type of mushroom. Mushrooms produce spores, but they consume seeds. Mushrooms must touch berries to get their seeds. If the berry cannot produce enough seeds for the mushroom, the mushroom produces less spores. If the berry produces more seeds than needed, the remaining seeds go to the regular seeds stack': '你j解锁了第一种蘑菇。蘑菇产生孢子，但它们消耗种子。蘑菇必须接触浆果才能获得种子。如果浆果不能为蘑菇产生足够的种子，蘑菇就会产生较少的孢子。如果浆果产生的种子比需要的多，剩下的种子就会被送到常规的种子堆里',
    'You unlocked the first type of mushroom! Mushrooms produce spores rather than seeds, and spores will be used by the tree.': '你解锁了第一种蘑菇!蘑菇产生孢子而不是种子，孢子会被树利用。',
    'XXIII, consumed': 'XXIII, 消耗',
    'XXII, consumed': 'XXII, 消耗',
    'XXI, consumed': 'XXI, 消耗',
    'XI, consumed': 'XI, 消耗',
    'X, consumed': 'X, 消耗',
    'XVII, consumed': 'XVII, 消耗',
    'Billion': '十亿',
    'Planted something on every single field cell. Time to delete crops when more room is needed!': '在每个野外单元上都种植一些东西。 需要更多空间的时候该删除农作物了！',
    'undo': '撤销',
    'upgrade': '升级',
    'to view them.': '查看它们。',
    'This game auto-saves every few minutes in local storage in the web browser, but please use': '本游戏每隔几分钟自动保存在浏览器本地存储，但请使用',
    'The upgrades also unlock permanent crops that produce seeds forever, unlike the short-lived watercress.': '升级还可以解锁永久作物，永久产生种子，而不像短命的西洋菜。',
    'The text in the message log at the bottom will guide you through how to play. A short summary of the first steps: initially you have no resources but can get some from clicking ferns. Then you can click on field tiles to plant crops and soon resources are gained automatically and soon after that permanently. The rest will be revealed when the time is ready.': '底部消息日志中的文字将指导你如何玩。对第一步的简短总结:最初您没有资源，但可以通过单击ferns获得一些资源。然后你可以点击田地瓷砖种植庄稼，很快资源就会自动获得，不久之后就会永久获得。剩下的事等时机成熟了再揭晓。',
    'Ethereal farm is an incremental game taking place on a field with a mysterious tree in the center. Most crops are permanent and there\'s no harvesting/selling/withering as in many farm games, instead it\'s about growing better and better plant types, with various neighbor-interaction rules with other plants in the field.': '《空灵农场》是一款发生在一块中央有一棵神秘树的土地上的增量游戏。大多数作物都是永久性的，不像许多农场游戏那样可以收获/出售/枯萎，相反地，它是关于种植越来越好的植物类型，并与地里的其他植物产生各种邻居互动规则。',
    'buy multiple abilities up to 25% of current available essence': '购买多种技能最多25%的当前可用精华',
    'buy as many of this upgrade as you can afford': '购买尽可能多的这种升级，在你可以负担的范围内',
    'A key no longer works since only 1 weather ability can be active at once now, use 1, 2 or 3 to enable an ability instead.': '一个钥匙不再起作用，因为现在只能激活一个天气技能，使用1,2或3来激活一个技能。',
    'was still growing, full refund given': '仍在成长，全额退款',
    'Deleted watercress. Since this is a short-lived plant, nothing is refunded': '删除西洋菜。 由于这是短寿命的植物，因此无法退还任何资源',
    'Viewed the main help dialog': '查看了主帮助对话框',
    'delete plant, only if this is enabled in preferences': '删除植物，仅在首选项中启用后',
    'close dialogs.': '关闭弹框.',
    'Upgrade blueberry': '升级蓝莓',
    'activate one of the weather abilities': '激活天气能力之一',
    'settings -> export save': '设置 -> 导出存档',
    'Savegame recovery': '游戏存档恢复',
    'save the undo state now, rather than load it. This overwrites your undo so eliminates any chance of undoing now. This will also be overwritten again if you do actions a minute later.': '现在保存撤消状态，而不是加载它。 这将覆盖您的撤消，因此消除了立即撤消的任何机会。 如果您在一分钟后执行操作，此操作也将再次被覆盖。',
    'replant watercress on all field tiles that have a watercress remainder, and refresh existing ones. Such a remainder appears for watercress that have been copying from multiple plants, that is, a good copying spot. Copying has diminishing returns if there are multiple watercress anywhere on the map, 1 or 2 is effective (check the seeds/s income to view the effect).': '在所有剩下西洋菜的田间地砖上重新种植西洋菜，并刷新现有的。 对于已经从多个植物中复制的西洋菜来说，这样的残留物是很好的复制点。 如果地图上的任何地方有多个西洋菜，则复制的收益递减，有效值为1或2（检查种子的收入以查看效果）。',
    'regularly for backups, because a local storage savegame can easily get lost.': '定期进行备份，因为本地存储保存游戏很容易丢失。',
    'plant a watercress (does not affect last planted type for shift key': '种植西洋菜（不影响上次种植的类型用Shift键',
    'plant last planted type': '种植上次种植的类型',
    'List of keyboard shortcuts': '快捷键列表',
    'import and old savegame, but do not run the time, so you get the resources at the time of saving rather than with all production during that time added.': '导入和旧的游戏存档，但不运行时间，这样你就可以在保存的时候获得资源，而不是添加那段时间的所有生产。',
    'If you plant watercress next to permanent plants, the watercress copy all its neighbors (orthogonal, not diagonal) production for free, so watercress remains relevant if you like to use it. If there is more than 1 watercress in the entire field this gives diminishing returns, so having 1 or perhaps 2 max makes sense (which is by design to not need to plant many of them all the time). The watercress is its own independent multiplier so it works well and is relevant no matter how high level other boosts the plant has later in the game.': '如果您在永久性植物旁边种植豆瓣，豆瓣可免费复制其所有邻居（正交，而非对角线）的产品，因此如果您愿意使用豆瓣，则豆瓣仍然很重要。 如果整个田间有超过1个西洋菜，这将使收益递减，因此具有1个或2个最大值是有道理的（这是设计使您不必一直种植很多）。 豆瓣菜是其自己的独立乘数，因此它运作良好，并且与植物后期在游戏中产生的高水平其他提升无关。',
    'If something goes wrong with your savegame, there may be a few older recovery savegames. Click': '如果您的游戏存档出现问题，则可能是一些较旧的恢复保存游戏。 请点击',
    'Symbol meanings': '符号含义',
    'Number Format help': '数字格式帮助',
    'WARNING: This is not a soft reset: nothing is kept, everything will be deleted, including achievements, settings and recovery saves. This starts over with a new, blank, savegame, and cannot be reverted. Are you sure you want to do this?': '警告：这不是软重置：不保留任何内容，所有内容都将被删除，包括成就，设置和恢复保存。 这将从新的空白游戏开始，并且无法还原。 你确定你要这么做吗？',
    'Perform a hard reset. This removes all savegame data, deletes your entire game and starts a new game from the beginning.': '执行硬重置。 这将删除所有保存的游戏数据，删除整个游戏并从头开始创建新游戏。',
    'Export a savegame backup: copy or download the encoded savegame below, and store it somewhere safe. Do this regularly: even though the game autosaves in the web browser, browsers can easily lose this data. This contains all your progress!': '导出存档游戏备份：复制或下载以下编码的游戏存档，并将其存储在安全的地方。 定期执行此操作：即使游戏在网络浏览器中自动保存，浏览器也很容易丢失这些数据。 这包含了您的所有进度！',
    'Remains of a watercress that was copying from multiple plants. Visual reminder of good copying-spot only, this is an empty field spot and does nothing. Allows replanting this watercress with "w" key.': '从多个植物复制的西洋菜的遗迹。 仅视觉提示良好的复制点，这是一个空白字段，不执行任何操作。 允许使用“ w”键重新种植西洋菜。',
    'Planted 5 or more permanent plants over the course of the game': '在游戏过程中种植了5棵或以上的永久植物',
    'Million': '百万',
    'Not yet earned. Unearned achievements are normally hidden, except hinted ones like this shown as "?': '尚未获得。 不劳而获的成果通常是隐藏的，除了那些暗示这样的显示为“？',
    'Export an encoded savegame, for backups.': '导出游戏的存档代码，以进行备份。',
    'Perform a hard reset. This removes all savegame data, deletes your entire game and starts a new game from the beginning.\n\nWARNING: This is not a soft reset: nothing is kept, everything will be deleted, including achievements, settings and recovery saves. This starts over with a new, blank, savegame, and cannot be reverted. Are you sure you want to do this?': '执行硬重置。 警告：这不是软重置：不保留任何内容，所有内容将被删除，包括成就，设置和恢复保存。这将删除所有保存的游戏数据，删除整个游戏并从头开始创建新游戏。 这将从新的空白游戏开始，并且无法还原。 你确定要这么做吗？',
    'Various UI, saving, gameplay and other settings.': '各种用户界面，保存，游戏和其他设置。',
    'Undo is saved when doing an action, but with at least a minute in-between, so multiple actions in quick succession may all be undone.': '执行操作时会保存撤消操作，但间隔至少一分钟，因此快速连续执行的多个操作都可能被撤消。',
    'Undo your last action(s). Press again to redo.': '撤消您的最后一个动作。 再按一次即可重做。',
    'No matter how long ago the undo was saved, you still get the correct produced resources now for that timespan.': '无论撤消保存了多久，现在仍可以在该时间范围内获得正确的生产资源。',
    ': to duplicate full production of long-lived berry and mushroom neighbors for free (mushroom copy also consumes more': '：免费复制长寿命的浆果和蘑菇邻居的完整产量（蘑菇副本也会消耗更多',
    'Thousand': '数千',
    'the entire field full of watercress': '整个田地都充满西洋菜',
    'short-lived': '短期',
    'short-lived.': '寿命短.',
    'berry': '浆果',
    'berry.': '浆果.',
    'blackberry.': '黑莓.',
    'crops...': '农作物...',
    'Produces seeds. Boosted by flowers. Negatively affected by nettles. Neighboring mushrooms can consume its seeds to produce spores. Neighboring watercress can copy its production.': '产生种子。 由花助长。 受到荨麻的负面影响。 邻近的蘑菇可以消耗其种子来产生孢子。 邻近的西洋菜可以复制其生产。',
    'Breakdown (production': '细目分类（生产',
    "base": "基础",
    'Tree level': '树等级',
    'Tip: use SHIFT key on the field to plant last plant type, or CTRL for watercress.': '提示：在字段上使用SHIFT键可以种植最后的植物类型，对于西洋菜则使用CTRL。',
    'TIP: hold SHIFT to plant last crop type, CTRL to plant watercress': '提示：按住SHIFT键可种植最后一种作物类型，按住CTRL键可种植西洋菜',
    'You have enough resources to plant. Click an empty field to plant': '你有足够的资源来种植。单击空地进行种植',
    'Viewed the player stats': '查看玩家数据',
    'Viewed the changelog': '查看更新日志',
    'upgrades': '升级',
    'blackberry. Base production: 4 seeds/s. Crop type: berry': '解锁新作物:黑莓。基地产量:每秒钟4粒。作物类型:浆果',
    'Time since beginning': '起始时间',
    'Time in this field': '在这个田野的时间',
    'Breakdown per crop type (as potential production': '按作物类型分类(作为潜在产量',
    'Adds 20%  time duration to the lifespan of watercress (additive), and adds 50% base production excluding the neighbor coppying effect. (additive': '将西洋菜的寿命延长20%(额外)，并将基础产量增加50%，排除邻近复制效应。(额外',
    'Ethereal winter upgrade now more useful: also upgrades those positive winter effects.': '现在更有用空灵的冬季升级：也提升了冬季的积极影响。',
    'Ethereal mushroom bonus improved: no longer increases consumption.': '空灵蘑菇奖励提高：不再增加消耗。',
    'Ethereal crops now give 100% resin back on delete, but require ethereal deletion tokens.': '空灵农作物现在会在删除时提供100％的树脂，但需要空灵删除标记。',
    'Delete crop and get some of its cost back.': '删除作物，收回一些成本。',
    'Copy ability: if this plant has resource-producing long-lived neighbors (orthogonal, not diagonal) of type berry or mushroom, the watercress will duplicate all their production (but also consumption), no matter how high their tier! This has diminishing returns if there are multiple watercress plants in the entire field, max 1 or 2 watercress makes sense. A badly placed watercress can even negatively affect the copying of all others. If you have no other crop types this is not yet relevant, plant as many watercress as you want then!': '复制能力：如果这种植物的浆果或蘑菇类型具有长寿命资源（邻居，而不是对角线），西洋菜将复制其所有产量（包括消耗量），无论其等级高高！ 如果整个田地中有多个西洋菜植物，则收益递减，最多1或2个西洋菜是有意义的。 放置不当的西洋菜甚至会对所有其他产品的复制产生负面影响。 如果您没有其他作物类型，那么这还不重要，那么您可以种植任意数量的西洋菜！',
    'Choose a crop to plant': '选择一种农作物',
    'Achievement production bonus: +': '成就生产加成: +',
    'Save to local storage now. The game also autosaves every few minutes so you don\'t need this button often.': '立即保存到本地存储。 游戏还会每隔几分钟自动保存一次，因此您不需要经常使用此按钮。',
    'Latin suffixes for large numbers, such as T for trillion, Qa for quadrillion, V for vigintillion, ...': '大数字的拉丁后缀，例如T表示万亿，Qa表示千万亿，V表示非常大的数字，…',
    'Ethereal upgrades are permanent and the resin is not refundable. You can also spend resin on plants in the ethereal field instead.': '空灵的升级是永久性的，树脂不予退款。 您也可以将树脂花在空灵领域的植物上。',
    'Click icon or see tooltip for more info': '单击图标或查看工具提示以获取更多信息',
    'Choose large number notation': '选择大数符号',
    'Change the precision and display type for large numbers.': '更改数字的精度和显示类型。',
    ', to use the up to date location please export your savegame (see under gear icon), visit the new location, and import your savegame there.': '，要使用最新位置，请导出您的游戏存档（请参见齿轮图标下方），访问新位置，然后将您的游戏存档导入该位置。',
    'or starter resources when there is no production yet.': '或尚无生产的入门资源。',
    'Once a fern appeared, letting it sit longer does not change the amount gives.': '一旦一株蕨类植物出现，让它停留的时间更长并不会改变它的数量。',
    'fern: provides some resource when activated.': '蕨菜：启动时提供了一些资源。',
    'Hold shift to buy as many as possible': '按住Shift键购买最大数量',
    'The amount is based on production at time when the fern appears,': '该数量基于蕨类植物出现时的产量，',
    'No further ethereal upgrades are available for now.': '目前没有进一步的空灵升级。',
    'Import a savegame backup. You can create a backup with "export save". Paste in here and press "import".': '导入游戏存档备份。 您可以使用“导出存档”创建备份。 粘贴在这里，然后按“导入”。',
    'Import a save, which you created with "export save': '导入您使用“导出存档”创建的存档代码',
    // 更新日志
    'A few other minor tweaks, e.g. the savegame now remembers which tab you had open and the assigned shift key plant.': '其他一些小的调整，例如 保存游戏现在可以记住您打开了哪个选项卡以及指定的Shift键种植。',
    'Added "a" keyboard shortcut for abilities.': '为功能添加了“ a”键盘快捷键。',
    'Added "choice" upgrades': '添加了“选择”升级',
    'Bugfixes': '修复Bug',
    'Changed the savegame format internally to be more compatible with future updates.': '内部更改了存档的格式，使其与将来的更新更加兼容。',
    'Fixed a minor exploit with ferns.': '修复了蕨类的小漏洞。',
    'Improve UI of "choice" upgrades to be single upgrade with a choice dialog': '使用选择对话框将“选择”升级的用户界面改进为单一升级',
    'Fixed bugs related to leeching and transcension II.': '修复了与盗取和超越II相关的错误。',
    'Renamed "fog ability" to "mist ability".': '将“雾能力”更名为“雾能力”。',
    'Only one weather ability can be active at the same time now.': '现在只能同时启用一个天气能力。',
    'Swapped fog and sun ability (sun is now unlocked first).': '交换了雾和太阳的能力（现在首先解锁了太阳）。',
    'UI tweaks and fixes.': 'UI调整和修复。',
    'Unused resin also gives a small boost now.': '现在，未使用的树脂也有小幅提升。',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    'watercress': '西洋菜',
    'watercress.': '西洋菜.',
    'Watercress': '西洋菜',
    'blueberry': '蓝莓',
    'Blueberry': '蓝莓',
    'blackberry': '黑莓',
    'Blackberry': '黑莓',
    'champignon': '香菇',
    'Champignon': '香菇',
    'cranberry': '蔓越莓',
    'Cranberry': '蔓越莓',
    'blackberry. Base production: 4 seeds/s. Crop type:': '黑莓。 基本产量：4种子/秒。 作物类型：',
    'blueberry. Base production: 1.4K seeds/s. Crop type:': '蓝莓。 基本产量：1.4K种子/秒。 作物类型：',
    'cranberry. Base production: 980K seeds/s. Crop type:': '蔓越莓。 基本产量：980K种子/秒。 作物类型：',
    'champignon. Base production: -980K seeds, 1 spores/s. Crop type:': '香菇。 基本产量：-980K种子，1孢子/秒。 作物类型：',
    'Quadrillion': 'Quadrillion',
    'Quintillion': 'Quintillion',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Season change in: ": "距离季节变化还有：",
    "• ": "• ",
    "notation: ": "符号：",
    "Welcome to Ethereal Farm ": "欢迎来到空灵农场",
    "This game requires JavaScript. The game runs fully locally.": "该游戏需要JavaScript。 游戏完全在本地运行。",
    "Game version: Ethereal Farm ": "游戏版本：空灵农场 ",
    "Buy: ": "购买: ",
    "Cost: ": "成本: ",
    "That fern gave": "蕨类植物给予",
    "available: ": "可用: ",
    "\"": "“",
    "Upgrade ": "升级 ",
    "Upgraded: Unlock ": "升级: 解锁 ",
    "Not enough resources to plant clover: need ": "没有足够的资源来种植三叶草：需要",
    "Not enough resources to plant blackberry: need ": "没有足够的资源来种植黑莓：需要",
    "Not enough resources to plant cranberry: need ": "没有足够的资源来种植酸果蔓：需要",
    'Copies neighbors': '复制邻居',
    "achievements: ": "成就: ",
    "Base planting cost": "基础种植成本",
    "Crop type: ": "农作物类型: ",
    "Growing time: ": "生长时间: ",
    'Last planting cost': '上次种植成本',
    "Unlock ": "解锁 ",
    "Plant ": "种植 ",
    "Upgraded: Upgrade ": "升级: 升级 ",
    "Not enough resources for upgrade: need ": "没有足够的资源进行升级：需要",
    "Living time: ": "生存时间: ",
    "Planting cost: ": "种植成本: ",
    "Short-lived plant. Time left: ": "寿命短的植物。 剩下的时间：",
    "Unlocks new crop: ": "解锁新作物: ",
    "blackberry ": "黑莓 ",
    "Tier ": "层 ",
    "Have over ": "有超过 ",
    "Achievement Unlocked": "成就解锁",
    "Achievement unlocked: ": "成就解锁: ",
    " upgrades (10): ": " 升级 (10): ",
    "no neighbors, not copying: none": "无邻居，不复制：无",
    "Deleted blueberry, got back": "删除蓝莓，回收",
    "Deleted blackberry, got back": "删除黑莓，回收",
    "shift + click ": "shift + 左键点击 ",
    "ctrl + click ": "ctrl + 左键点击 ",
    "Not enough resources to plant blueberry: need ": "没有足够的资源来种植蓝莓：需要",
    'Auto-saved state locally': '本地自动保存状态',
    "blueberry ": "蓝莓 ",
    'Growing. Time to grow left': '生长中。 成长剩余时间',
    "champignon ": "香菇 ",
    "Large time delta: ": "大时间差：",
    "Choice: ": "选择: ",
    "level ": "等级 ",
    "Next level requires: ": "下一级需要：",
    "Potential production (": "潜在产量(",
    "Young sprout level ": "幼芽等级",
    "cranberry ": "蔓越莓",
    "Expected production/sec:": "预期产量/秒：",
    "Efficiency: ": "效率：",
    "Potential max production: ": "最大潜在产量：",
    "Deleted champignon, got back": "删除香菇，回收",
    "Satisfied: ": "满意：",
    "Ability: Growing speed": "能力：成长速度",
    "Ability: Weather cooldown": "能力：天气冷却",
    "Fruit essence available: ": "可用的水果精华：",
    "Get on sacrifice: ": "牺牲: ",
    "Growing speed ": "成长速度",
    "Level up: ": "升级: ",
    "Weather cooldown ": "天气冷却",
    "Young tree level ": "幼树级别",
    "After consumption: ": "消费后:",
    "champignon: ": "香菇：",
    "clover ": "三叶草",
    "Cooldown time: ": "冷却时间: ",
    "Total cycle: ": "总周期：",
    "watercress: ": "西洋菜：",
    "Young tree": "幼树",
    "currant ": "黑醋栗",
    "Type:": "类型:",
    "Growth time:": "成长时间:",
    "Crop info (": "作物信息(",
    "Ability:": "能力:",
    "chosen:": "选择:",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "time: ": "时间: ",
    "Have 1 fullgrown ": "拥有一棵成熟的",
    "Have 10 fullgrown ": "拥有一棵成熟的",
    "Have 20 fullgrown ": "拥有一棵成熟的",
    "Fruit: zinc apple: ": "水果:锌苹果:",
    "ethereal ": "空灵",
    "Ethereal ": "空灵",
    "Effect: ": "效果: ",
    "Neighbor boost:": "邻居提升:",
    "Next tree level requires:": "下一级树需要:",
    "Fruit: bronze apple: ": "水果:青铜苹果:",
    "Season change in:": "季节变化剩余时间:",
    "watercress ": "西洋菜 ",
    "Next planting cost: ": "下一个种植成本: ",
    "Recoup on delete: ": "删除后收回：",
    "Production/sec:": "产量/秒:",
    "Production per second": "每秒产量",
    "Produces a small amount of seeds on its own, but can produce much more resources by copying from berry and mushroom neighbors once you have those": "自己产生少量种子，但是一旦有了这些种子，可以通过从浆果和蘑菇邻居那里复制而产生更多的资源",
    "Planted watercress. Consumed: 10 seeds. Next costs: 10 seeds (": "种植西洋菜。 消耗：10种子。 下一个成本：10种子（",
    "Next planting cost: 10 seeds (": "下次种植成本:10粒种子 (",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    "\"": "\”",
    " seeds": " 种子",
    " seeds.": " 种子.",
    " I": " I",
    " bonus to flower boost": "加成给花提升",
    " seeds (": " 种子 (",
    " minute": " 分钟",
    " minute.": " 分钟.",
    " berry": " 浆果",
    " seeds, have": " 种子, 有",
    "gained at once": "立即获得",
    " mushroom": " 蘑菇",
    " spore": " 孢子",
    " essence": " 精华",
    "": "",
    "": "",
    "": "",
    "": "",
    " seeds/spore": " 种子/孢子",
    ", consumed": ", 消耗",
    "consumed": "消耗",
    " spores": "孢子",
    "minutes": "分钟",
    "consumed": "消耗",
    ": Silver": ": 银",
    ": Zinc": ": 锌",
    ": Bronze": ": 铜",
    ": bronze": ": 铜",
    " of stacks": " 堆叠",
    " of stacks) (": " 堆叠) (",
    " of stacks).": " 堆叠).",
    "seeds,": "种子,",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^(.+) seeds, have: (.+) seeds \($/, '$1 种子, 拥有: $2 种子 \('],
    [/^(.+) seeds, have$/, '$1 种子, 拥有'],
    [/^Planted currant. Consumed: (.+) seeds. Next costs: (.+) 种子(.+)$/, '种植黑醋栗。 消耗：$1 种子。 下一个成本：$2 种子$3'],
    [/^Planted clover. Consumed: (.+) seeds. Next costs: (.+) 种子(.+)$/, '种植三叶草。 消耗：$1 种子。 下一个成本：$2 种子$3'],
    [/^Planted champignon. Consumed: (.+) seeds. Next costs: (.+) 种子(.+)$/, '种植香菇。 消耗：$1 种子。 下一个成本：$2 种子$3'],
    [/^Planted cranberry. Consumed: (.+) seeds. Next costs: (.+) 种子(.+)$/, '种植蔓越莓。 消耗：$1 种子。 下一个成本：$2 种子$3'],
    [/^Planted blackberry. Consumed: (.+) seeds. Next costs: (.+) 种子(.+)$/, '种植黑莓。 消耗：$1 种子。 下一个成本：$2 种子$3'],
    [/^Planted blueberry. Consumed: (.+) seeds. Next costs: (.+) 种子(.+)$/, '种植黑莓。 消耗：$1 种子。 下一个成本：$2 种子$3'],
    [/^(.+) seeds \((.+)$/, '$1 种子 \($2'],
    [/^(.+) seeds \($/, '$1 种子 \('],
    [/^Planted (.+) or more permanent plants over the course of the game$/, '在游戏过程中种植$1棵或更多永久植物'],
    [/^Tree leveled up to: young tree, level (.+). Consumed: (.+) spores. Tree boost: (.+)\%. Resin added: (.+). Total resin ready"$/, '升级到:幼树，第$1级。消费:$2孢子。树提高:$3\%。树脂补充道:$4。总树脂准备'],
    [/^The season changed, it is now summer. Income before: (.+) seeds, (.+) spores. Income now: (.+) seeds,$/, '季节改变了，现在是夏天。 以前的收入：$1种子，$2孢子。 现在的收入：$3种子，'],
    [/^Tree leveled up to: young sprout, level (.+). Consumed: (.+) spores. Tree boost: (.+)\%. Resin added: (.+). Total resin ready$/, '树木升至：新芽，等级$1。消耗：$2孢子。 树木助力：$3\%。 添加的树脂：$4。 总树脂准备就绪'],
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^([\d\.]+) minutes ([\d\.]+) seconds.$/, '$1 分钟 $2 秒.'],
    [/^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s.$/, '$1 小时 $2 分钟 $3 秒.'],
    [/^(.+) seeds, (.+) spores$/, '$1 种子, $2 孢子'],
    [/^升级: 升级 (.+), consumed: (.+) 种子$/, '升级: 升级 $1, 消耗: $2 种子'],
    [/^blackberry (.+), $/, '黑莓 $1, 消耗'],
    [/^watercress (.+), $/, '西洋菜 $1, 消耗'],
    [/^(.+) minutes (.+) seconds \(base$/, '$1 分 $2秒 \(基于'],
    [/^(.+) seeds,$/, '$1 种子,'],
    [/^(.+) spores \((.+)h (.+)m$/, '$1 孢子 \($2小时 $3分'],
    [/^(.+) seeds \((.+)\%$/, '$1 种子 \($2\%'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);
